### ISSUE TITLE
Could not find reference pixel, unpause script to try again

### ISSUE THREAD

**Issue by DUBIONv** [dice4321/Gunkolle#16]
I'm playing at 1280x720 res and using Nox emulator, i have tried both "compatible" and "speed" rendering modes with no change.

Both master and test branches give the same error

**Comment by dice4321** [comment]
Others have come to me in the past with the same problem, something is changing the color of the pixels and I have no idea have to replicate it. I've tried to change the NOX DPI, change nvidia settings and nothing seems to change. If this exact pixel isnt the required RGB hex color, the script wont work.

![](https://i.imgur.com/qdSNeEo.png)

**Comment by DUBIONv** [comment]
![12323413214332](https://user-images.githubusercontent.com/35168306/42823878-56be6354-89e7-11e8-8125-b027f6fb4818.png) 

i'll try to fiddle around my settings but i have no idea what could be causing this 🤔

**Comment by DUBIONv** [comment]
After trying out a lot various settings on 2 different PC's (amd & intel gpus) i would guess different gpu's handle the antialiasing of the in-game elements differently and as the pixelsearch relies on edge pixels the script will only work on nvidia systems.

**Comment by dice4321** [comment]
Oh, very interesting find. Thanks for this, I'll update the requirements.
