### ISSUE TITLE
0-2 

### ISSUE THREAD

**Issue by riseri** [dice4321/Gunkolle#17]
when starting the second turn, it keeps looping by selecting and deselecting DragSquad

**Comment by dice4321** [comment]
interesting, who is your squad leader?

**Comment by riseri** [comment]
G11 was my squad leader at the time.

**Comment by dice4321** [comment]
I changed the location of the dragger check a tiny bit lower, let me know if you still have this problem.

**Comment by riseri** [comment]
Still having the same problem.

**Comment by dice4321** [comment]
Works for me, https://streamable.com/tgcpl
The only problems I can think of are, if you downloaded the wrong branch, or your screen drag didnt drag all the way to the top.

**Comment by riseri** [comment]
Seems the problem for me was with the file DragSquadClicked.png. Replacing it with a different file solved it for me.

**Comment by dice4321** [comment]
alright
