### ISSUE TITLE
Need help with Combat count before end turn

### ISSUE THREAD

**Issue by l2aYza** [dice4321/Gunkolle#18]
I've tried to make Gunkolle works on JP server but I can't find some of an image source.

edit: I got It's work somehow now I have got a new problem with combat pause not working correctly

After AHK executed planning mode After the first battle, it's continuously tapping which result pause planning mode.

**Comment by dice4321** [comment]
Sorry I couldn't get to your question, its because its trying to confirm that it has entered combat by finding the pause button at the top of the screen when it has indeed entered combat.
