### ISSUE TITLE
stuck on formation...?

### ISSUE THREAD

**Issue by sasahara00** [dice4321/Gunkolle#23]
after its Ready 
when I click start, 

preparing to send sorties
starting sortie in 00:00:003

Gunkolle is set it on fromation

nothing happens here and on.
am I doing anything wrong?

**Comment by dice4321** [comment]
Since the formation button also depends on your background, it could be that you have a different background than the default one.

**Comment by sasahara00** [comment]
yes i do have different background,
after changing the background to default I can move on to actual battle thanks
