### ISSUE TITLE
G11 & M4A1

### ISSUE THREAD

**Issue by kuzmma** [dice4321/Gunkolle#25]
I'm not sure what happened but whenever I choose my G11 as one of the to swap dolls it is detecting M4A1'S pixels and choosing her instead. Was working fine for a long time until maybe this update but not sure.

**Comment by dice4321** [comment]
Yeah, the pixels on the profile change everytime new girls get to lvl 100 and the profile pictures get shifted around a bit. I'll try to change it one more time, but if it still doesnt work for you, your best bet is to add the assets yourself.
