### ISSUE TITLE
is there way to stop disassemble other dolls after battle?

### ISSUE THREAD

**Issue by sasahara00** [dice4321/Gunkolle#26]
would rather do that manually since I need to use large number of them,

if this is too much of change please discard the request, 

thank you in advance

**Comment by dice4321** [comment]
Alright, update to the new 0.4.5 version and set your DisassembleCycle to 999 and it should do as you want.

**Comment by sasahara00** [comment]
thank you for such a quick update!
how ever when I start 0.4.5 version I get on error of "Map or world invalid. Press enter after each field to submit"

older version works fine, as usual ..

**Comment by sasahara00** [comment]
on version 0.4.4 if you set Enchantment=20 (didn't try anything higher)
it stops disassembling dolls or does enchantment.

I am not sure how to get 0.4.5 to work ..

**Comment by sasahara00** [comment]
now on new 0.4.5, 

after formation, its unable to select dolls (carry), stuck on confirm

**Comment by dice4321** [comment]
If your having trouble with finding the <doll>Profile picture, you're going to have to create your own asset.

**Comment by sasahara00** [comment]
0.4.4 works fine, so I used assets from 0.4.4,
if I use assests from 4.4 its gets more bugger, it starts to removes 4th character and fail to switch dolls for drag. i'll try to create my own assets file and try to make 4.5 going

**Comment by dice4321** [comment]
I know why that bug is happening. Going from the home screen to the formation screen, if it doesnt find the formation screen within 10 seconds, the script starts aggressively clicking the resend expedition button then back at the formation button until it finds formation screen. It works for me, but I should change that. Does it take a long time to load from the home page to the formation screen for you?

**Comment by dice4321** [comment]
Alright I fixed the problem with the 4th character bug, that shouldnt happen anymore, and went ahead and changed the 'Endturn' aswell, it should be fine just as long as you replace those carry doll assets. Also its not the 'Enchancement' you want to change to 20, its the 'DisassembleCycle' you want to change to 20 in 0.4.5.

**Comment by sasahara00** [comment]
alright I will try it out,

thank you
