### ISSUE TITLE
start combat hangs from time to time

### ISSUE THREAD

**Issue by gucciandablade** [dice4321/Gunkolle#29]
every now and then it'll just hang and the script tries to resupply without starting the map

**Comment by dice4321** [comment]
Im going to need a screenshot of where it hangs and at exactly what picture the script is trying to click in the output box.

**Comment by gucciandablade** [comment]
![hangs](https://user-images.githubusercontent.com/42957756/45061635-2d65ed80-b05a-11e8-9549-4069efe920e3.png)
it pretty much gets stuck here for 30-45 seconds then gives up and tries to resupply without starting the run. this happens about 3-5 times a day at most.

**Comment by gucciandablade** [comment]
alright i'm gonna test it right now. it might be the same issue with ending the run as well since that glows too.

**Comment by gucciandablade** [comment]
![0 0](https://user-images.githubusercontent.com/42957756/45115581-192afa80-b105-11e8-8a9d-3ac4ae78afde.png)
alright so it hung up at the end round

**Comment by dice4321** [comment]
hmmmm, it got to the '0 0' part, that means it click something.... maybe the round combat around ended and it clicked the end round image too fast for the game to register the click, going to add a sleep inbetween then.

**Comment by gucciandablade** [comment]
94 solid runs so far
