### ISSUE TITLE
Nothing happen after start

### ISSUE THREAD

**Issue by EliteProofer** [dice4321/Gunkolle#30]
It just says formation. I have started on menu and did all steps following wiki

**Comment by dice4321** [comment]
The formation button also relies on the background of your home screen, it needs to be the default background, is your background different?

**Comment by EliteProofer** [comment]
nope, the background is default, the t doll is ump 45. I switched to speed but nothing happen.

**Comment by EliteProofer** [comment]
nvm the problem is resolved after I restolred the default window size. more troubles in selecting m4a1 currently says filter

**Comment by dice4321** [comment]
So youre at the formation screen and you have M4A1 on one of the first two slots?

**Comment by dice4321** [comment]
Not sure what the problem is, I'm testing both compatible and speed mode and they both come out to be positive for a match.

![](https://i.imgur.com/DQIaFex.png)

**Comment by EliteProofer** [comment]
how do you use the debugger? gonna test to see if ti detect the image

**Comment by dice4321** [comment]
you need to put 'dx' in the parameters. Go to line 169 in gunkolle.ahk and replace the line with `FindClick(A_ScriptDir "\pics\" x, y "Center x" RandX " y"  RandY " o" SearchNumber)`

**Comment by EliteProofer** [comment]
i opened the gunkoille after repaling 169 and saving it but no difference? no debugger

**Comment by dice4321** [comment]
So click back into the formation screen, did it find M4A1?

**Comment by EliteProofer** [comment]
yes it did. but the debugger screen is behind the nox player, so I moved the nox player, which moved the coordinates. so I relaunched everything, and now the debugger won't launch again, and its stuck on formation...

**Comment by EliteProofer** [comment]
removed the dx, leaving a space before the o.  it can now go smoothly until confirm, after slecting filter.

**Comment by dice4321** [comment]
I really cant pinpoint the problem if something is working one second then the next second its not working.   Since the changing of the screen size was a problem twice, maybe try locking the screen, 

![](https://i.imgur.com/gddAQ4b.png)

**Comment by EliteProofer** [comment]
well thanks for the help. I set fixed window size and after I did that it ran smoothly past the ecehlon confirm page. however I forgot to set it to chapter 4 so it couldnt continue... meaning I had to restart it... which leads to it being stuck again, at the same point. 

The program is fine just ;ll gonna try on differnt computer

**Comment by EliteProofer** [comment]
finally solved the issue was f.lux changing screen color making the pictures not able to identify images.

**Comment by dice4321** [comment]
Weird, I have f.lux as well but it doesn't affect me.
