### ISSUE TITLE
filter issue

### ISSUE THREAD

**Issue by gucciandablade** [dice4321/Gunkolle#31]
**Desktop:**
evga gtx 960

**Config File:**
https://pastebin.com/3sjX9pqS

**Describe the bug**
so after about 85 continuous runs, the corpse drag filter started to mess up. it selected my 5th doll instead of the carry. will test some more tomorrow.

**Screenshots**
kinda forgot to do this. ill update it tomorrow.

**Comment by dice4321** [comment]
Damn, I'm not even sure how it can select the 5th doll of the echelon if the Image search before the filter is literally restricted to the first two slot. Im gonna need some images for sure.

**Comment by gucciandablade** [comment]
the update yesterday where you added the new assets for the filter might have fixed this but i'll do more testing. i also updated my drivers to 399.07 if that matters.
