### ISSUE TITLE
system unable to select 5 star AR 

### ISSUE THREAD

**Issue by sasahara00** [dice4321/Gunkolle#32]
**Desktop:**
What graphics card are you using?
1080ti

**Config File:**

[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=TYPE95
Doll2=M4SOPMODII
WeaponType=AssaultRifle
DisassembleCycle=55
ProductionTdoll=0
ProductionEquipment=0
Enchancement=0
LastXS=2698
LastYS=173

**Describe the bug**

so for now, it does not select 5 starts when its choose to select from assault rifles..
was going to edit 4 star image asset on my own but could not find the file it self.

other problems I was facing before all got fixed, if two guns are chosen from 4 stars it runs smooth. 

**Screenshots**
https://imgur.com/a/Q3TxF7S

**Comment by dice4321** [comment]
It searches for 4 stars both times?

**Comment by sasahara00** [comment]
correct

**Comment by dice4321** [comment]
Hmmm, now that I look at them, those two images look almost like a carbon copy of each other, I'll replace them, thanks for the report!

**Comment by sasahara00** [comment]
well.. now it only selects 5-stars and can't select 4 star...

**Comment by dice4321** [comment]
Ah, nah dont be sorry, I'm glad someone else is trying to make use of my work. I dont know if its a logic error or the image search is really messing up, I think I'll search for something else to see if that'll work on your end.

**Comment by sasahara00** [comment]
works fine after 0.4.6 update 

thank you so much
