### ISSUE TITLE
Logistics Timing

### ISSUE THREAD

**Issue by gucciandablade** [dice4321/Gunkolle#33]
**Desktop:**
gtx 960

**Config File:**
[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=G11
Doll2=AR15
WeaponType=AssaultRifle
DisassembleCycle=3
ProductionTdoll=0
ProductionEquipment=0
Enchancement=0
LastXS=2224
LastYS=0

**Describe the bug**
logistics will cancel the retirement process if they overlap.

**Screenshots**
https://streamable.com/e2qgi

**Comment by dice4321** [comment]
Alright, should be fixed in the latest update 0.4.5.1
