### ISSUE TITLE
0-2 testing

### ISSUE THREAD

**Issue by gucciandablade** [dice4321/Gunkolle#37]
**Desktop:**
gtx 960

**Config File:**
https://pastebin.com/HpLH9JDf

**Describe the bug**
1. script get's stuck "dragsquad" on turn 2 (will get a video of this when i can
2. script doesn't go into planning mode on turn 2 and moves 1 spot (video below)

**Video**
1. coming soon kek
2. https://streamable.com/wwx2l

**Comment by dice4321** [comment]
Oh, I forgot to put an offset when I updated the clicking pattern, thanks for the report!
