### ISSUE TITLE
on 4-3e run, sometimes it fails to resupply before the turn

### ISSUE THREAD

**Issue by sasahara00** [dice4321/Gunkolle#39]
**Describe the bug**
when single damage dealer is in the command post, 
on every 15-20 runs, it fails to resupply before the turn, 

it just skips resupplying and continues to battle,
so in next run, our squad has no ammo to fight,

only happens on 4-3e run
0-2 run never had this problem.

version 4.7.0

default config

**Comment by dice4321** [comment]
Image realignment caused by the change in click pattern, fixed.
