### ISSUE TITLE
ExpeditionArrive/Confirm loop

### ISSUE THREAD

**Issue by riseri** [dice4321/Gunkolle#41]
**Desktop:**
1070ti

**Config File:**
[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=FAL
Doll2=M4SOPMODII
WeaponType=AssaultRifle
DisassembleCycle=3
ProductionTdoll=0
ProductionEquipment=0
Enchancement=1
FriendCollector=1
BatteryCollector=1
LastXS=3420
LastYS=47

**Describe the bug**
It keeps looping ExpeditionArrive/Confirm in the echelon formation screen.

**Screenshots**
https://streamable.com/oefta

**Comment by dice4321** [comment]
From the looks of it, its stuck in a loop trying to find the "WaitForFormation" image. The odd thing is that it got past the first screen, so im going to take a guess that you replaced the Formation image on your own. The only conclusion I can draw from this, is that you replaced the formation image while the nox window size was not at the proper size, the script recongizes the first image, but not the "WaitForFormation" image.

**Comment by riseri** [comment]
Ah, seems like the issue was a stupid one because the image for "WaitForFormation" was different from the previous versions. I just imported the images from previous versions to new ones.
