### ISSUE TITLE
Expedition only error

### ISSUE THREAD

**Issue by sasahara00** [dice4321/Gunkolle#43]
when I click Expedition only, system goes "Initial Event notice Found"
and goes in to profile page,

and soon it leaves the profile page but, when expedition comes,
it fails to accept,

when you start botting on any level than pause, click expedition only
than it works fine, by going in to factory. 

can not replicate this problem 100%
sometimes, it works fine to begin with, 

I can tell its working if it goes to factory randomly
and if it goes to profile randomly it is not working.

version 4.7.2

but for people who are having same problem
just run one random map, pause, check expedition only and, resume (click pause again) this fixes the problem.

**Comment by dice4321** [comment]
That is just the oddest thing, can you send me a picture of your yellow arrow at the bottom of your home screen like this 

![image](https://user-images.githubusercontent.com/20022859/45583017-020bab80-b86f-11e8-8345-2a0c3748c3ca.png)

**Comment by sasahara00** [comment]
this stopped happening after the update.

will close the thread.
