### ISSUE TITLE
Would it be possible to add SVD to the list of guns you could use?

### ISSUE THREAD

**Issue by sjk0603** [dice4321/Gunkolle#44]
I see that WA2000 is available, would it be possible for the bot to select SVD as well? 

I think WA2000 and SVD would be the best rifles to use for dragging 3-2N.

**Comment by dice4321** [comment]
Certainly possible, the only thing is, I have yet to pull SVD myself so I am unable to provide the assets heh. 
As for best dolls to use in 3-2N, I would argue that 9A91 and OTS14 are far superior to rifles. Use a UMP to tank and you can have a 4 man buff squad for your AR. Enough damage to use 1 repair ticket every 20 runs.

**Comment by sjk0603** [comment]
Oh, I see, I'll use those guns instead.
