### ISSUE TITLE
New Client

### ISSUE THREAD

**Issue by BuffaloFrail** [dice4321/Gunkolle#46]
Hi Dice,
I believe that as your script uses textures to select buttons, the upcoming client update on the 16th will likely break it. How difficult would it be to replace each of the images with their new client counterparts?

Also, side note, but if there are no dolls present for retiring when the retirement script runs, the script will break and get stuck, and need to be restarted. Other than that, it works great!

**Comment by dice4321** [comment]
If I documented everything well enough for myself to know what the script is doing, it should take around 10-20 seconds per image to replace. If they replaced the assets for the Tdoll images, God help us all.

As for the side question, Im curious as to what map you're running that produces zero Tdoll drops? Or did you set the DisassembleCycle to 1 and not getting any drops?

**Comment by BuffaloFrail** [comment]
It's not so much that I'm running maps that don't drop dolls, and more enabled the enhancement cycle will use up all the fodder, and if you fail to get a 3* drop (which happens a lot in 3 cycles of 4-3e) then you'll have nothing to scrap.

**Comment by dice4321** [comment]
oh this is very true, I will look into this problem.
