### ISSUE TITLE
0.4.7.5.2 - battle error 4-3e

### ISSUE THREAD

**Issue by sasahara00** [dice4321/Gunkolle#50]
unable to click 4-3e battle page,
- after going to 4-3e page its unable to actually click to start

If I click 4-3e manually it proceeds without much problem,
screenshot attached on exactly where it is stuck

https://ibb.co/hvweaf

** seems like its 4_3e image giving problem, I re-captured the image to work for me, but fix is need in batch file, ( image file capture on 4-3 doesn't work because background changes (?), I captured image file for the power level instead to make it work )

thank you, as always <3

**Comment by sasahara00** [comment]
also, 50% chance Resupply doesn't work
I need to click my solo corpse leader maually to start Resupplying

**Comment by dice4321** [comment]
Gotcha, the 4_3e problem was caused because the script would click 4-3e too fast when the UI was transitioning from the normal maps to emergency maps. I'll try to re-position the 4_3eCommandPostResupply. It works on my end, tell me if the problem continues and I'll try another method of fixing it.

**Comment by sasahara00** [comment]
its working fine now, thank you
