### ISSUE TITLE
Random wait values not doing anything

### ISSUE THREAD

**Issue by enjokousai** [dice4321/Gunkolle#51]
![untitled](https://user-images.githubusercontent.com/44253522/47133847-3b17bf80-d2f6-11e8-8c4f-ba06ea39342b.jpg)

Occasionally, the script would hang at this point because it would click on the heliport too quickly after starting the map making it unable to find HeliPortResuply2. I have tried changing the min and max random wait values to compensate but as far as I can tell, the clicks are always the same speed regardless of what it is set to.

**Comment by dice4321** [comment]
I cant really seem to recreate the problem with clicking the HeliPortResupply2 even with zero sleep in-between the two, but I did manage to fix the min and max sleep, give that a try.

**Comment by enjokousai** [comment]
With the random wait speeds working everything is working fine again.
