### ISSUE TITLE
Script run error

### ISSUE THREAD

**Issue by Neno42** [dice4321/Gunkolle#53]
**Desktop:**
What graphics card are you using? 1080ti 

**Config File:**
Post your Config File
Default Config file. 
**Describe the bug**
Running Gunkolle.ahk gives this error.

**Screenshots**
![ukb1tkv](https://user-images.githubusercontent.com/34979025/47273009-87b00480-d55b-11e8-8e98-92eae99bbe6b.png)

**Comment by dice4321** [comment]
Wow, I forgot to add that line in the last update and no one told me in the last two days, is anyone updating Q.Q

Thank you for the report!
