### ISSUE TITLE
Issue with enhancement/retirement?

### ISSUE THREAD

**Issue by sjk0603** [dice4321/Gunkolle#66]
It seems to run into this issue often when it's time for enhancement/retirement.

![image](https://user-images.githubusercontent.com/43340980/49057669-929b2c00-f1ce-11e8-9269-5c3d86b2c1a0.png)

**Comment by dice4321** [comment]
Can I see where the script stopped running?

**Comment by sjk0603** [comment]
![image](https://user-images.githubusercontent.com/43340980/49070128-f33f5e80-f1f8-11e8-83a6-96280424a193.png)

It went through the first few cycles of enhancement/retirement just fine, and then it happened again at this specific phase.

I should note that the last time it happened was after on the second round of enhancement/retirement.

**Comment by dice4321** [comment]
Alright, can you try out the change I just did.

**Comment by sjk0603** [comment]
![image](https://user-images.githubusercontent.com/43340980/49082261-56d88480-f217-11e8-9f7a-114e2ac06737.png)
![image](https://user-images.githubusercontent.com/43340980/49082266-59d37500-f217-11e8-97fd-774953891abd.png)

**Comment by dice4321** [comment]
ohman, the first fix might have worked, but then it gets stuck in the next image... what on earth..

**Comment by dice4321** [comment]
Found the problem, the expedition checker was clicking the green parts of the construction whenever it went into factory. Try it now.

**Comment by sjk0603** [comment]
18 runs and no issues so far!

It seems like it's been resolved, but I'll keep it running over night to make sure. Thank you for all your hard work!
