### ISSUE TITLE
Anyone updated for new client yet?

### ISSUE THREAD

**Issue by ReversalGM** [dice4321/Gunkolle#78]
Anyone fixed the script and want to release it? 

edit: nvm looks like echocontrol fixed it. had to change up the expedition only mode slightly though.

**Comment by CearDeedum** [comment]
Did you run into a problem with running 0-2, I can't seem to get the scroll function working again after the patch.

**Comment by EchoControl** [comment]
@CearDeedum What nox version are you on? I have somewhat same issue when it wouldn't scroll for full screen or would ignore input. Also, be sure to run it while EN layout is on.

**Comment by EchoControl** [comment]
@EliteProofer Hasn't checked the expedition only mode. Can you share it?

**Comment by CearDeedum** [comment]
I am currently running the 6.1.0.0 client, but even with the 6.0.8.0 client I still had the same problem, I think with the 6.1.0.0 client, I have been facing more client crashes/google play stop working errors

**Comment by Koivaa** [comment]
For me it's started crashing after Nvidia drivers update, but changing nox version helped then. Google play stops happen occasionally. I can only suggest updating gpu drivers and to fiddle with different nox versions and settings

**Comment by EchoControl** [comment]
For me it's started crashing after Nvidia drivers update, but changing nox version helped then. Google play stops happen occasionally. I can only suggest updating gpu drivers and to fiddle with different nox versions and settings

**Comment by ReversalGM** [comment]
@EchoControl 
its a crude solution. the script seems to detect what pops up depending on pixel color? anyways i just replaced 

Else
			{	
				GuiControl,, NB, Initial Event notice Found
				ClickS(Dailypopx,Dailypopy)
				loopcount++
			}

with

Else
			{	
				GuiControl,, NB, Initial Event notice Found
				RFindClick("ExpeditionArrive", "rNoxPlayer mc o50 w30000,50")
				RFindClick("ExpeditionConfirm", "rNoxPlayer mc o50 w30000,50")
				loopcount++
			}

doesn't catch daily logins.  will have to look into that another time, hopefully replacing all the pixel codes.

**Comment by EchoControl** [comment]
@EliteProofer Hm, it also needs autobattle then. I'll add it today
Thanks!

**Comment by EchoControl** [comment]
@EliteProofer I've added your solution, just in case.
