### ISSUE TITLE
Nox crash after update

### ISSUE THREAD

**Issue by Lacerta556** [dice4321/Gunkolle#79]
I have this problem after the client updated. Nox always crash after ran 0-2 around 10 - 20 rounds either in OpenGL or DirectX mode. Does anyone encounter this issue? also, the AHK only works for some specific Nox version. I tried the latest version but didn't work.

**Comment by EchoControl** [comment]
@Lacerta556 Same was for me but on 6.0.8.0 version of NOX. 6.1.0.0 version works fine

**Comment by Lacerta556** [comment]
@EchoControl Thanks! the 6.1 version really fix this.
